#!/usr/bin/env python3
"""Seed da biblioteca de referência de prompts do Content Engine OS.

Uso:
  python3 scripts/seed_prompt_reference_library.py --print-sql > db/init/012_seed_prompt_reference_library.sql
  python3 scripts/seed_prompt_reference_library.py --write-csv
  python3 scripts/seed_prompt_reference_library.py --json-summary
"""
from __future__ import annotations
import argparse
import csv
import io
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "knowledge/prompt-intelligence/prompt_reference_library_ivs_20260715.json"
CSV = ROOT / "knowledge/prompt-intelligence/prompt_reference_library_ivs_20260715.csv"


def q(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''") + "'"


def jq(value):
    return q(json.dumps(value, ensure_ascii=False)) + "::jsonb"


def load():
    return json.loads(LIB.read_text(encoding="utf-8"))


def print_sql(data):
    print("-- generated by scripts/seed_prompt_reference_library.py")
    print("-- run after db/init/012_prompt_reference_library.sql")
    for source in data["sources"]:
        print(
            "insert into prompt_reference_sources "
            "(source_key,name,url,source_type,access_status,primary_use,notes,raw_payload) values "
            f"({q(source['source_key'])},{q(source['name'])},{q(source['url'])},{q(source['source_type'])},"
            f"{q(source['access_status'])},{q(source['primary_use'])},{q(source['notes'])},{jq(source)}) "
            "on conflict (source_key) do update set "
            "name=excluded.name,url=excluded.url,source_type=excluded.source_type,"
            "access_status=excluded.access_status,primary_use=excluded.primary_use,"
            "notes=excluded.notes,raw_payload=excluded.raw_payload,updated_at=now();"
        )
    for pattern in data["patterns"]:
        print(
            "insert into prompt_reference_patterns "
            "(pattern_key,pattern_type,label,description,default_risk) values "
            f"({q(pattern['pattern_key'])},{q(pattern['pattern_type'])},{q(pattern['label'])},"
            f"{q(pattern['description'])},{q(pattern['default_risk'])}) "
            "on conflict (pattern_key) do update set "
            "pattern_type=excluded.pattern_type,label=excluded.label,description=excluded.description,"
            "default_risk=excluded.default_risk,updated_at=now();"
        )
    for prompt in data["prompts"]:
        print(
            "insert into prompt_reference_prompts "
            "(code,source_key,pattern_key,format,channel,title,raw_prompt_structure,ivs_adapted_prompt,negative_prompt,objective,risk_level,required_gate,status,tags) values "
            f"({q(prompt['code'])},{q(prompt['source_key'])},{q(prompt['pattern_key'])},{q(prompt['format'])},"
            f"{q(prompt['channel'])},{q(prompt['title'])},{q(prompt['raw_prompt_structure'])},"
            f"{q(prompt['ivs_adapted_prompt'])},{q(prompt['negative_prompt'])},{q(prompt['objective'])},"
            f"{q(prompt['risk_level'])},{q(prompt['required_gate'])},{q(prompt['status'])},{jq([])}) "
            "on conflict (code) do update set "
            "source_key=excluded.source_key,pattern_key=excluded.pattern_key,format=excluded.format,"
            "channel=excluded.channel,title=excluded.title,raw_prompt_structure=excluded.raw_prompt_structure,"
            "ivs_adapted_prompt=excluded.ivs_adapted_prompt,negative_prompt=excluded.negative_prompt,"
            "objective=excluded.objective,risk_level=excluded.risk_level,required_gate=excluded.required_gate,"
            "status=excluded.status,updated_at=now();"
        )
    evidence = {
        "json": str(LIB),
        "csv": str(CSV),
        "source_doc": "https://docs.google.com/document/d/1WbxqsE54ooepiJM75KRWZeLzW7fPLqqq1gPewEHdwXo/mobilebasic",
        "note": "Seed inicial a partir do doc '3 Free Websites for AI Prompts'; prompts externos foram destilados e adaptados IVS-first."
    }
    print(
        "insert into prompt_reference_ingest_runs "
        "(source,source_doc_url,prompts_count,sources_count,patterns_count,status,evidence) values "
        f"('google_doc_prompt_reference',{q(evidence['source_doc'])},{len(data['prompts'])},{len(data['sources'])},{len(data['patterns'])},'done',{jq(evidence)});"
    )


def write_csv(data):
    rows = data["prompts"]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)
    CSV.write_text(output.getvalue(), encoding="utf-8")
    return CSV


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--print-sql", action="store_true")
    parser.add_argument("--write-csv", action="store_true")
    parser.add_argument("--json-summary", action="store_true")
    args = parser.parse_args()
    data = load()
    if args.print_sql:
        print_sql(data)
        return 0
    if args.write_csv:
        path = write_csv(data)
        print(json.dumps({"ok": True, "csv": str(path)}, ensure_ascii=False))
        return 0
    if args.json_summary:
        print(json.dumps({
            "ok": True,
            "sources": len(data["sources"]),
            "patterns": len(data["patterns"]),
            "prompts": len(data["prompts"]),
            "json": str(LIB),
            "csv": str(CSV),
        }, ensure_ascii=False, indent=2))
        return 0
    print("Use --print-sql, --write-csv ou --json-summary")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
