'use client';
import { useState } from 'react';
import { api } from '@/lib/api'; import type { Hook } from '@/lib/types'; import styles from './HookCard.module.css';
const labels:Record<string,string>={clarity:'Clareza',specificity:'Especificidade',novelty:'Novidade',retention:'Retenção',channel_fit:'Aderência'};
async function copyText(text:string){try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();document.execCommand('copy');area.remove()}}
export function HookCard({hook,selected=false,onCompare}:{hook:Hook;selected?:boolean;onCompare?:(hook:Hook)=>void}){const [copied,setCopied]=useState(false);const [favorite,setFavorite]=useState(Boolean(hook.favorite));const [favoriteError,setFavoriteError]=useState(false);const blocked=hook.compliance.status==='block';
 async function favor(){if(favorite)return;setFavoriteError(false);try{await api.favorite(hook.id);setFavorite(true)}catch{setFavoriteError(true)}}
 async function copy(){await copyText(hook.text);setCopied(true)}
 return <article className={styles.card} aria-label={`Hook: ${hook.text}`}><header><span className={`${styles.status} ${styles[hook.compliance.status]}`}>{hook.compliance.status==='pass'?'Aprovado na checagem':hook.compliance.status==='review'?'Requer revisão':'Bloqueado'}</span><span className={styles.pattern}>{hook.pattern_id}</span></header><blockquote>{hook.text}</blockquote><div className={styles.score}><strong>{Math.round(hook.scores.overall)}</strong><span>Score geral</span></div><dl className={styles.dimensions}>{Object.entries(labels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{Math.round(hook.scores[key as keyof typeof hook.scores])}</dd></div>)}</dl><p className={styles.explain}><b>{hook.mechanisms.join(', ')}</b> · {hook.explanation}</p>{hook.compliance.reasons.length>0&&<p className={styles.reasons}>Motivos: {hook.compliance.reasons.join('; ')}</p>}<footer><button type="button" onClick={copy}>{copied?'Copiado':'Copiar'}</button><button type="button" onClick={favor} aria-pressed={favorite}>{favorite?'Favoritado':'Favoritar'}</button><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('adapt-hook',{detail:{topic:hook.topic,text:hook.text}}))}>Adaptar</button><button type="button" disabled={blocked} aria-pressed={selected} title={blocked?'Hooks bloqueados não podem ser comparados':undefined} onClick={()=>onCompare?.(hook)}>{selected?'Remover da comparação':'Comparar'}</button></footer>{favoriteError&&<small role="alert">Não foi possível favoritar.</small>}</article>}
